/**
 * Core TypeScript type definitions for the Trade Builder application
 * 
 * These types define the structure of indicators, algorithms, and related data
 * used throughout the application.
 */

/**
 * Technical indicator type
 * Represents a single technical indicator (e.g., RSI, MACD, SMA)
 */
export interface Indicator {
  id: string;
  name: string;
  category: 'momentum' | 'trend' | 'volatility' | 'volume';
  description: string;
  parameters: IndicatorParameter[];
}

/**
 * Parameter for configuring an indicator
 * Each indicator can have multiple parameters (e.g., period, standard deviations)
 */
export interface IndicatorParameter {
  name: string;
  type: 'number' | 'select';
  defaultValue: number | string;
  min?: number;
  max?: number;
  options?: string[];
}

/**
 * User's trading algorithm configuration
 * Represents a complete algorithm with weighted indicators
 */
export interface AlgorithmConfig {
  id: string;
  name: string;
  description: string;
  indicators: WeightedIndicator[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * An indicator with its weight and custom settings
 * Weight determines how much influence this indicator has (0-100)
 */
export interface WeightedIndicator {
  indicator: Indicator;
  weight: number; // 0-100
  settings: Record<string, number | string>;
}

/**
 * Backtest result for an algorithm
 * Contains performance metrics and trade history
 */
export interface BacktestResult {
  algorithmId: string;
  symbol: string;
  startDate: Date;
  endDate: Date;
  initialCapital: number;
  finalCapital: number;
  totalReturn: number; // Percentage
  sharpeRatio: number;
  maxDrawdown: number; // Percentage
  winRate: number; // Percentage
  totalTrades: number;
  trades: Trade[];
}

/**
 * Individual trade in a backtest or paper trading session
 */
export interface Trade {
  id: string;
  timestamp: Date;
  type: 'buy' | 'sell';
  symbol: string;
  price: number;
  quantity: number;
  value: number;
  reason?: string; // Why this trade was made (for education)
}

/**
 * Virtual portfolio for paper trading
 */
export interface Portfolio {
  id: string;
  name: string;
  cash: number;
  positions: Position[];
  totalValue: number;
  createdAt: Date;
}

/**
 * A position in a portfolio
 */
export interface Position {
  symbol: string;
  quantity: number;
  averagePrice: number;
  currentPrice: number;
  value: number;
  unrealizedPL: number;
  unrealizedPLPercent: number;
}

/**
 * Market data point (OHLCV)
 */
export interface MarketData {
  timestamp: Date;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

/**
 * Calculated indicator values
 */
export interface IndicatorValues {
  indicatorId: string;
  timestamp: Date[];
  values: number[] | { [key: string]: number[] }; // Single value or multiple series
}

/**
 * Trading signal generated by an algorithm
 */
export interface TradingSignal {
  timestamp: Date;
  type: 'buy' | 'sell' | 'hold';
  strength: number; // 0-100, confidence in the signal
  indicators: {
    id: string;
    value: number;
    contribution: number; // How much this indicator contributed to the signal
  }[];
}

/**
 * User trading personality profile
 */
export interface TradingPersonality {
  userId: string;
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';
  tradingStyle: 'day-trader' | 'swing-trader' | 'long-term';
  preferredIndicators: string[];
  avgHoldingPeriod: number; // in days
  behaviorMetrics: {
    impulsiveness: number; // 0-100
    patience: number; // 0-100
    consistency: number; // 0-100
  };
}
